name: Sync Data
on:
  issues:
    types: [opened]

jobs:
  update-data:
    if: startsWith(github.event.issue.title, 'DATA_UPDATE')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update data.json
        run: |
          echo '${{ github.event.issue.body }}' > data.json
      - name: Commit change
        run: |
          git config --global user.name 'DataBot'
          git config --global user.email 'bot@isprs.org'
          git add data.json
          git commit -m "Automated data update"
          git push
      - name: Close Issue
        run: |
          gh issue close ${{ github.event.issue.number }} --confirm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
